### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by ferradeira** [BlinkTagInc/gtfs-to-html#127]
Hello,

I installed gtfs-to-html on Ubuntu Ubuntu 20.04.3 LTS.
Always get a syntax error:
# gtfs-to-html
/usr/local/lib/node_modules/gtfs-to-html/bin/gtfs-to-html.js:3
import yargs from 'yargs';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Thanks

**Comment by brendannee** [comment]
Make sure you are using node.js version 14 or greater.

**Comment by ferradeira** [comment]
I installed version 17, but now I get this error:
Error: libnode.so.64: cannot open shared object file: No such file or directory
don't know what to install
thanks

**Comment by brendannee** [comment]
This sounds like an issue with your node.js installation.

You could try:
    sudo apt install libnode64


https://stackoverflow.com/questions/69378783/node-error-while-loading-shared-libraries-libnode-so-72
