### ISSUE TITLE
errors with @vscode/sqlite3 node module

### ISSUE THREAD

**Issue by wkulesza** [BlinkTagInc/gtfs-to-html#133]
Hi,
this is not a problem of gtfs-to-html itself, but related to nvm, but will still give a try.
trying to install this with the following command:
npm install gtfs-to-html --build-from-source --unsafe-perm --allow-root -g

and getting this:
```
> @vscode/sqlite3@5.0.7 install /root/.nvm/versions/node/v14.18.1/lib/node_modules/gtfs-to-html/node_modules/@vscode/sqlite3
> node-gyp rebuild

make: Wejście do katalogu '/root/.nvm/versions/node/v14.18.1/lib/node_modules/gtfs-to-html/node_modules/@vscode/sqlite3/build'
  CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
  AR(target) Release/obj.target/../../node-addon-api/nothing.a
  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3360000/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3360000/sqlite3.c] Błąd 127
make: Opuszczenie katalogu '/root/.nvm/versions/node/v14.18.1/lib/node_modules/gtfs-to-html/node_modules/@vscode/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.4.0-90-generic
gyp ERR! command "/root/.nvm/versions/node/v14.18.1/bin/node" "/root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v14.18.1/lib/node_modules/gtfs-to-html/node_modules/@vscode/sqlite3
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vscode/sqlite3@5.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vscode/sqlite3@5.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-01T09_52_11_559Z-debug.log
```

Tried all solutions, including uninstalling node, reinstalling, trying different versions (now using nvm use 14.18.1) with no luck..

Any hints ? Tried also using node with snap (but it got node 10 so too low for gtfs-to-html)

**Comment by wkulesza** [comment]
@brendannee mark as closed and solved please.

my solution was:
```
sudo ln -s /usr/bin/python3 /usr/bin/python
```
as i had no python command in console, just python3...

**Comment by brendannee** [comment]
Great solution.  I'm testing out a version that uses a different node.js sqlite library, so hopefully this issue will be resolved in the future.
