### ISSUE TITLE
$and/$nor/$or must be a nonempty array

### ISSUE THREAD

**Issue by zackkrida** [BlinkTagInc/gtfs-to-html#37]
Using the following `config.json`:

```json
{
  "mongoUrl": "mongodb://localhost:27017/ripta",
  "agencies": [
    {
      "agency_key": "rhode-island-public-transit-authority",
      "url": "http://transitfeeds.com/p/rhode-island-public-transit-authority/363/latest/download"
    }
  ],
  "beautify": true,
  "coordinatePrecision": 5,
  "effectiveDate": "July 8, 2016",
  "menuType": "jump",
  "noServiceSymbol": "—",
  "requestStopSymbol": "***",
  "showMap": true,
  "showOnlyTimepoint": true,
  "showStopCity": false,
  "mapboxAccessToken": "pk.eyJ1IjoiemFja2tyaWRhIiwiYSI6ImNqNWticTdlODF6MGYycWxtaWRqMGNlNnYifQ.hNazsLyjg5s20C6vwOEZKg",
  "zipOutput": false
}
```

and running `gtfs-to-html --configPath config.json`, I get the following output:

```
Starting GTFS import for 1 file
rhode-island-public-transit-authority: Downloading GTFS from http://transitfeeds.com/p/rhode-island-public-transit-authority/363/latest/download
rhode-island-public-transit-authority: Download successful
rhode-island-public-transit-authority: Importing GTFS from /Users/developers/Desktop/ripta-gts-html-test/downloads/rhode-island-public-transit-authority-gtfs.zip
rhode-island-public-transit-authority: Importing - agency.txt - 1 lines imported
rhode-island-public-transit-authority: Importing - calendar_dates.txt - 207 lines imported
rhode-island-public-transit-authority: Importing - calendar.txt - No file found
rhode-island-public-transit-authority: Importing - fare_attributes.txt - No file found
rhode-island-public-transit-authority: Importing - fare_rules.txt - No file found
rhode-island-public-transit-authority: Importing - feed_info.txt - No file found
rhode-island-public-transit-authority: Importing - frequencies.txt - No file found
rhode-island-public-transit-authority: Importing - routes.txt - 54 lines imported
rhode-island-public-transit-authority: Importing - shapes.txt - 102424 lines imported
rhode-island-public-transit-authority: Importing - stop_times.txt - 235391 lines imported
rhode-island-public-transit-authority: Importing - stops.txt - 3612 lines imported
rhode-island-public-transit-authority: Importing - transfers.txt - No file found
rhode-island-public-transit-authority: Importing - trips.txt - 5616 lines imported
rhode-island-public-transit-authority: Post Processing data
rhode-island-public-transit-authority: Completed
Completed GTFS import for 1 file
{ MongoError: $and/$or/$nor must be a nonempty arrayof 107 HTML schedules
    at Function.MongoError.create (/usr/local/lib/node_modules/gtfs-to-html/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/usr/local/lib/node_modules/gtfs-to-html/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /usr/local/lib/node_modules/gtfs-to-html/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  name: 'MongoError',
  message: '$and/$or/$nor must be a nonempty array',
  ok: 0,
  errmsg: '$and/$or/$nor must be a nonempty array',
  code: 2,
  codeName: 'BadValue' }
```

Any ideas? Thanks for any help!

**Comment by brendannee** [comment]
Thanks for reporting this issue.

I looked at the GTFS feed you are using and it is missing the required `calendar.txt` which was causing some issues.

Despite this, I pushed an update that better handles GTFS without a `calendar.txt`, even though this is technically required by the GTFS spec. See the new gtfs-to-html version 0.10.3 and try it out.

**Comment by zackkrida** [comment]
Wow, appreciate the support and fast reply. This seems like a great lib and I'm excited to dig into it further -- thanks!
