### ISSUE TITLE
Win10: gtfs-to-html fails on unexpected token.

### ISSUE THREAD

**Issue by jspetrak** [BlinkTagInc/gtfs-to-html#39]
### Environment

```
PS C:\Users\jspet> npm -v
3.10.10
```

### Error

```
PS C:\Users\jspet> gtfs-to-html --configPath .\config-travelsupport.json
C:\Users\jspet\AppData\Roaming\npm\node_modules\gtfs-to-html\bin\gtfs-to-html.js:39
const getConfig = async () => {
                        ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

### Config file

```
{
	"agencies" : [
		{
			"path" : "C:\Users\jspet\Workspace\travelsupport-data\Ex1_PRG-OLO-OSR-KRK"
		},
		{
			"path" : "C:\Users\jspet\Workspace\travelsupport-data\Ex3_PRG-PED-BRQ-Breclav"
		},
		{
			"path" : "C:\Users\jspet\Workspace\travelsupport-data\Ex3_PRG-PED-BRQ-BTS-BUD"
		},
		{
			"path" : "C:\Users\jspet\Workspace\travelsupport-data\Ex3_PRG-PED-BRQ-VIE-GRZ"
		}
	]
}
```

**Comment by brendannee** [comment]
Make sure you have node.js version 8.1.4 or higher.
