### ISSUE TITLE
.zip files generated by Mac

### ISSUE THREAD

**Issue by lonniusmax** [BlinkTagInc/gtfs-to-html#45]
I'm running OS X 10.11.6 and when I create a zip file using the compression option gtfs-to-html fails (error below). It works fine if I use the .zip file that's posted to our transit feed. However, if I open the zip file and then immediately compress the contents, the resulting zip file generates an error. Is there some difference in the way the Mac compresses the file, or is there something else happening?

Starting GTFS import for 1 file
[Agency]: Importing GTFS from /[location]/google_transit.zip
[Agency]: Importing - agency.txt - No file found
[Agency]: Importing - calendar_dates.txt - No file found
[Agency]: Importing - calendar.txt - No file found
[Agency]: Importing - fare_attributes.txt - No file found
[Agency]: Importing - fare_rules.txt - No file found
[Agency]: Importing - feed_info.txt - No file found
[Agency]: Importing - frequencies.txt - No file found
[Agency]: Importing - routes.txt - No file found
[Agency]: Importing - shapes.txt - No file found
[Agency]: Importing - stop_times.txt - No file found
[Agency]: Importing - stops.txt - No file found
[Agency]: Importing - transfers.txt - No file found
[Agency]: Importing - trips.txt - No file found
[Agency]: Post Processing data
[Agency]: Completed GTFS import
Completed GTFS import for 1 file
Error: No agency found for agency_key=[Agency]
    at Object.exports.generateOverviewHTML (/[location]/gtfs-to-html/lib/utils.js:586:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by brendannee** [comment]
Make sure that the zip file doesn’t create a folder. It should only contain
the .txt files, not a folder of them.
