### ISSUE TITLE
Getting "TypeError: Cannot convert undefined or null to object" when running gtfs-to-html

### ISSUE THREAD

**Issue by Muved** [BlinkTagInc/gtfs-to-html#47]
Hi there,

I'm currently having an issue when running `gtfs-to-html` which will prompt me with the following error:
```
Starting GTFS import for 1 file
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at executeOperation (C:\Users\smarcotte\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\mongodb\lib\utils.js:386:14)
    at Collection.remove (C:\Users\smarcotte\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\mongodb\lib\collection.js:1239:10)
    at NativeCollection.(anonymous function) [as remove] (C:\Users\smarcotte\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:139:28)
    at Promise.all.models.map.model (C:\Users\smarcotte\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\gtfs\lib\import.js:53:35)
    at Array.map (<anonymous>)
    at removeData (C:\Users\smarcotte\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\gtfs\lib\import.js:52:29)
    at Object.module.exports [as import] (C:\Users\smarcotte\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\gtfs\lib\import.js:323:13)
    at <anonymous>
```
Here is my config file:
```
{
  "mongoUrl": "mongodb://localhost:27017/gtfs",
  "agencies": [
    {
      "agency_key": "stm3",
      "path": "gtfs/gtfs_stm.zip"
    }
  ],
  "beautify": false,
  "coordinatePrecision": 5,
  "effectiveDate": "July 8, 2016",
  "menuType": "jump",
  "noServiceSymbol": "—",
  "requestStopSymbol": "***",
  "interpolatedStopSymbol": "•",
  "showMap": false,
  "showOnlyTimepoint": false,
  "showStopCity": false,
  "mapboxAccessToken": "",
  "zipOutput": false
}
```
And here is the mongod log:
```
2018-02-27T18:00:49.620-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:50579 #6 (6 connections now open)
2018-02-27T18:00:49.648-0500 I NETWORK  [conn6] received client metadata from 127.0.0.1:50579 conn: { driver: { name: "nodejs", version: "3.0.2" }, os: { type: "Windows_NT", name: "win32", architecture: "x64", version: "10.0.14393" }, platform: "Node.js v8.9.4,
 LE, mongodb-core: 3.0.2" }
2018-02-27T18:00:49.917-0500 I NETWORK  [conn6] end connection 127.0.0.1:50579 (5 connections now open)
```
Any help would be welcome. 😄

**Comment by brendannee** [comment]
Thanks for reporting this.

There is an issue in the node-gtfs library that this package uses on windows. https://github.com/BlinkTagInc/node-gtfs/issues/90

If you use a slightly older version of gtfs-to-html you shoudl not have this issue: 1.3.5: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.13.5

    npm install gtfs-to-html@1.3.5

**Comment by Muved** [comment]
Using version 0.13.5 fixes my issue. Thank you!

**Comment by brendannee** [comment]
The latest version of gtfs-to-html 0.13.9 uses the updated mongoose library which solves this issue on Windows: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.13.9

Please try it out and let me know if you have any issues.
